[package]
name = "term_tarot"
version = "0.1.0"
authors = ["Andrew Swanson <andrew@swanso.net>"]
edition = "2018"

[dependencies]

serde = { version = "1.0", features = [ "derive"] }
serde_json = "1.0"
rand = "0.7.0"
tui = "0.5"
clap = "2.33.0"
pager = "0.15.0"
dialoguer = "0.5.0"
